
spring:
  mail:
    host: smtp.qq.com # SMTP服务器地址
    port: 465 # 端口
    username: u369s@qq.com # 邮箱用户名
    password: xzityfybfvcwcaja # 邮箱密码
    properties.mail.smtp:
      auth: true
      ssl.enable: true
  rabbitmq:
    host: 116.62.32.192
    port: 5672
    username: admin
    password: 123456
  data:
    redis:
      database: 0
      # Redis数据库索引（默认为0）
      # Redis服务器地址
      host: 116.62.32.192
      # Redis服务器连接端口
      port: 6379
      # 连接池最大连接数（使用负值表示没有限制）
      jedis.pool.max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      jedis.pool.max-wait: -1
      # 连接池中的最大空闲连接
      jedis.pool.max-idle: 8
      # 连接池中的最小空闲连接
      jedis.pool.min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 5000
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://116.62.32.192:3306/dwq?serverTime=UTC
      username: root
      password: 123456dwq
      hikari:
        maximumPoolSize: 20
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 3
      limit: 5000
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
server:
  port: 8080
